volumes:
  db_data:
  
services:
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: hummingbird
      POSTGRES_PASSWORD: hummingbird
      POSTGRES_DB: hummingbird
    ports:
      - '5432:5432'
